### PR TITLE
feat(modules): add kızlarsoruyor, onedio and evrimagaci modules

### PR DESCRIPTION
**Pull request by Kadermiyanyedi**
Incorporated new modules into the project, inspired by the eksisozluk module. As these modules closely resemble existing functionality, comprehensive testing was deemed unnecessary.

### CODE REVIEW

**Comment by Kadermiyanyedi** [comment]
@realsuayip can you review this PR please? :D

**Review by realsuayip — CHANGES_REQUESTED** [review]
import new modules in

`yoklama/__init__`

**Comment by Kadermiyanyedi** [comment]
> import new modules in
> 
> `yoklama/__init__`

Done :D Can you review again please @realsuayip

**Comment by realsuayip** [comment]
merged!

@Kadermiyanyedi 

we'll need a `slugify` feature in `Module.get_value` for modules like `kizlarsoruyor.com` as they seem to be autogenerating username from given unicode string.

**Pull request merged**
